apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  storageClassName: gp2
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce

  # accessModes:
  #   - ReadWriteOnce
  # resources:
  #   requests:
  #     storage: 20Gi
  # volumeMode: Filesystem
  # storageClassName: gp2
  # volumeBindingMode: Immediate
   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:  
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
      containers:
        - name: mysql
          image: mysql:latest
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "1234"
            - name: MYSQL_DATABASE
              value: "test"
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_PASSWORD
              value: "1234"
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306



apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-default-consul-consul-server-1
  labels:
    type: local
spec:
  storageClassName: fast-disks
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"